version: 2

models:
  - name: customers
    access: public
    latest_version: 1
    config:
      materialized: table
      contract:
        enforced: true
    columns:
      - name: customer_id
        data_type: integer
      - name: customer_name
        data_type: varchar
      - name: customer_status
        data_type: varchar
    data_tests:
      - semantic_rails_contracts.semantic_rails_required_columns:
          arguments:
            required_columns:
              - customer_id
              - customer_name
    versions:
      - v: 1

sources:
  - name: app
    schema: main
    tables:
      - name: raw_customers
        identifier: raw_customers
        columns:
          - name: customer_id
            data_type: integer
          - name: customer_name
            data_type: varchar

seeds:
  - name: contract_seed
    columns:
      - name: seed_id
        data_type: integer
      - name: seed_name
        data_type: varchar

snapshots:
  - name: contract_seed_snapshot
    columns:
      - name: seed_id
        data_type: integer
      - name: seed_name
        data_type: varchar
