name: semantic_rails_contracts_connector_customers
version: 1.0.0
config-version: 2

profile: semantic_rails_contracts_connector_customers

model-paths: ["models"]
clean-targets:
  - target
  - dbt_packages
  - logs

require-dbt-version: [">=1.11.2", "<2.0.0"]
